name: Docker Image CI

on:
  release:
    types: [ "published" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read    
      packages: write   

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define image name and lowercase release tag
        id: vars
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}"
          TAG="${{ github.event.release.tag_name }}"
          LOWER_TAG="${TAG,,}"
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "release_tag=$LOWER_TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.release_tag }}
            ${{ steps.vars.outputs.image_name }}:latest
